

```{r}
defensive_positions = c("IDL", "ED", "CB", "LB", "S")
offensive_positions = c("QB", "RB", "WR", "LT", "RT", "RG", "LG", "C", "TE")
offensive_line = c("LT", "RT", "LG", "RG", "C")
special_teams = c("LS", "K", "P")
```


VISUALIZING THE QB SPLIT

```{r}
seasonal_breakdowns |>
  filter(position == "QB", season >= 2012) |>
  ggplot(aes(x = total_cap_pct))+
  geom_histogram(bins = 30)+
  labs(x = "% of Salary Cap", y = "Count", title = "Histogram of % of Salary Cap Allocated to Quarterback")

```



```{r}
seasonal_breakdowns |>
  filter(position == "QB", season >= 2012) |>
  ggplot(aes(x = total_cap_pct))+
  geom_histogram(bins = 30)+
  facet_wrap(~season) +
  labs(x = "% of Salary Cap", y = "count", title = "Histogram of % of Salary Cap Allocated to Quarterback by Season")
  
```

VISUALIZING PLANS BASED ON THE SPLIT


```{r}
high_value_QBs <- seasonal_breakdowns |>
  filter(QB >= 0.13, wins >= 8)
```



```{r}
low_value_QBs <- seasonal_breakdowns |>
  filter(QB <= 0.13, wins >= 8)
```

```{r}
high_value_QBs_summary <- high_value_QBs |>
  group_by(season, position) |>
  summarize(avg_total_cap_pct = mean(total_cap_pct), value = "high value")
```



```{r}
low_value_QBs_summary <- low_value_QBs |>
  group_by(season, position) |>
  summarize(avg_total_cap_pct = mean(total_cap_pct), value = "low value")
```

```{r}
value_comparison <- rbind(high_value_QBs_summary, 
                               low_value_QBs_summary)
```


```{r}
value_comparison |>
  filter(position %in% offensive_positions & !(position %in% offensive_line)) |>
  ggplot(aes(x = season, y = avg_total_cap_pct, color = value)) + 
  geom_point() + 
  geom_line() +
  facet_wrap(~position) +
  labs(x = "Season", y = "Average Salary Cap Allocation", 
       title = "Season-by-Season Cap Allocation to Skill Positions by Quarterback Value", 
       color = "Quarterback Value\n") + 
  scale_color_manual(labels = c("High Value Quarterback", "Low Value Quarterback"), 
                     values = c("blue", "red"))
```

```{r}
value_comparison |>
  filter(position %in% offensive_line) |>
  ggplot(aes(x = season, y = avg_total_cap_pct, color = value)) + 
  geom_point() + 
  geom_line() +
  facet_wrap(~position) +
  labs(x = "Season", y = "Average Salary Cap Allocation", 
       title = "Season-by-Season Cap Allocation to Offensive Line by Quarterback Value", 
       color = "Quarterback Value\n") + 
  scale_color_manual(labels = c("High Value Quarterback", "Low Value Quarterback"), 
                     values = c("blue", "red"))
```


```{r}
value_comparison |>
  filter(position %in% defensive_positions) |>
  ggplot(aes(x = season, y = avg_total_cap_pct, color = value)) + 
  geom_point() + 
  geom_line() +
  facet_wrap(~position) +
  labs(x = "Season", y = "Average Salary Cap Allocation", 
       title = "Season-by-Season Cap Allocation to Defensive Positions by Quarterback Value", 
       color = "Quarterback Value\n") + 
  scale_color_manual(labels = c("High Value Quarterback", "Low Value Quarterback"), 
                     values = c("blue", "red"))
```






